"""
Django settings for paramount_holidayz project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-iv+1l8$m&-!0&f22g(tv#6x6!r+&^vb_ih7yw_&#0rg1v#%2ci'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'paramountholidayz.com',
    'www.paramountholidayz.com',
    'paramount-holidayz-production.up.railway.app',
]
ALLOWED_HOSTS += [host for host in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if host]
CSRF_TRUSTED_ORIGINS = [
    'https://paramount-holidayz-production.up.railway.app',
    'https://paramountholidayz.com',
    'https://www.paramountholidayz.com',
]


# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_SSL_REDIRECT = True  # Set to True in production with HTTPS
SECURE_SSL_REDIRECT = os.getenv('DJANGO_SECURE_SSL_REDIRECT', 'True') == 'True'  # Set to True in production with HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SESSION_COOKIE_SECURE = True  # Set to True in production with HTTPS
CSRF_COOKIE_SECURE = True  # Set to True in production with HTTPS
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Use SMTP for sending emails
EMAIL_HOST = 'mail.paramountholidayz.com'  # Your SMTP server
EMAIL_PORT = 465  # SSL port
EMAIL_USE_SSL = True  # Use SSL for port 465
EMAIL_USE_TLS = False  # Don't use TLS with SSL
EMAIL_HOST_USER = 'india@paramountholidayz.com'  # Your email
EMAIL_HOST_PASSWORD = 'India@2025'  # Your email password
DEFAULT_FROM_EMAIL = 'india@paramountholidayz.com'  # Your email


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'holidays',
